%% logger.m
% MATLAB script for ADC data logging (from Arduino)
%
% MATLAB role:
% - Send configuration commands to Arduino
% - Start/stop interrogation
% - Receive combined ADS124S08 + ADS1299 data
% - Save clean CSV and Excel files
% - Plot selected signals live

clear; clc; close all;

%% =========================
% User settings
% ==========================

port = "/dev/cu.usbmodem1101";
baud = 115200;

% "SIM" before PCB/ADS testing.
% "ADS" once ADS124S08 and ADS1299 driver functions are implemented.
mode = "SIM";

% Streamed data sampling rate; separate from the CV step timing.
fs = 100;            % Hz

% One full CV cycle is 40 s with these settings.
% to capture a full forward-reverse cycle, duration has to be longer.
duration_s = 45;     % seconds

% CV settings sent to Arduino.
cvStart = -0.4;      % V
cvVertex = 0.6;      % V
cvStep = 0.005;      % V
cvScanRate = 0.05;   % V/s

csvFilename = "interrogation_combined_data.csv";
excelFilename = "interrogation_combined_data.xlsx";

%% Expected Arduino packet columns

columnNames = ["sample_counter", "timestamp_us", "time_s", ...
               "cv_potential", "dac_voltage", "dac_code", "phase", ...
               "AMP_GLU_V", "AMP_LAC_V", "AMP_PYR_V", "POT_K_V", ...
               "AMP_GLU_A", "AMP_LAC_A", "AMP_PYR_A", ...
               "ECOG1_V", "ECOG2_V", "ECOG3_V", "ECOG4_V", ...
               "ECOG5_V", "ECOG6_V", "EEG1_V", "EEG2_V"];

numExpectedColumns = numel(columnNames);

%% =========================
% Open serial
% ==========================

disp("Opening serial port...");

s = serialport(port, baud);
configureTerminator(s, "LF");
flush(s);

pause(2);

disp("Reading Arduino startup messages...");
while s.NumBytesAvailable > 0
    disp(strtrim(readline(s)));
end

%% =========================
% Configure Arduino
% ==========================

disp(" ");
disp("===== CONFIGURING ARDUINO =====");

sendCommand(s, "PING");
sendCommand(s, "STOP");
sendCommand(s, "SET_MODE " + mode);
sendCommand(s, sprintf("SET_RATE %.2f", fs));
sendCommand(s, sprintf("SET_CV %.4f %.4f %.4f %.4f", ...
    cvStart, cvVertex, cvStep, cvScanRate));
sendCommand(s, "STATUS");

disp("================================");
disp(" ");

%% =========================
% Prepare storage
% ==========================

dataMatrix = [];
badPackets = 0;
validPackets = 0;
headerReceived = false;

%% =========================
% Prepare live plots
% ==========================

figure("Name", "Arduino-controlled combined interrogation");

subplot(4,1,1);
cvLine = animatedline("LineWidth", 1.2);
grid on;
xlabel("Time / s");
ylabel("CV / V");
title("CV potential generated by Arduino");

subplot(4,1,2);
gluLine = animatedline("LineWidth", 1.2);
hold on;
lacLine = animatedline("LineWidth", 1.2);
pyrLine = animatedline("LineWidth", 1.2);
grid on;
xlabel("Time / s");
ylabel("Current / A");
title("ADS124S08-derived amperometric currents");
legend("Glucose", "Lactate", "Pyruvate", "Location", "best");

subplot(4,1,3);
potLine = animatedline("LineWidth", 1.2);
grid on;
xlabel("Time / s");
ylabel("Voltage / V");
title("Potentiometric channel");

subplot(4,1,4);
ecogLine = animatedline("LineWidth", 1.2);
hold on;
eegLine = animatedline("LineWidth", 1.2);
grid on;
xlabel("Time / s");
ylabel("Voltage / V");
title("ADS1299 neural channels");
legend("ECOG1", "EEG1", "Location", "best");

%% =========================
% Start interrogation
% ==========================

writeline(s, "START_INT");

disp("Interrogation running...");

tStart = tic;

while toc(tStart) < duration_s

    if s.NumBytesAvailable > 0

        line = strtrim(readline(s));

        if startsWith(line, "ACK")
            disp("Arduino: " + line);

        elseif startsWith(line, "HEADER")
            disp("Received Arduino header:");
            disp(line);
            headerReceived = true;

        elseif startsWith(line, "DATA")
            [valid, values] = parseArduinoDataLine(line, numExpectedColumns);

            if valid
                validPackets = validPackets + 1;
                dataMatrix(end+1, :) = values;

                % Column mapping:
                % 1 sample_counter
                % 2 timestamp_us
                % 3 time_s
                % 4 cv_potential
                % 5 dac_voltage
                % 6 dac_code
                % 7 phase
                % 8 AMP_GLU_V
                % 9 AMP_LAC_V
                % 10 AMP_PYR_V
                % 11 POT_K_V
                % 12 AMP_GLU_A
                % 13 AMP_LAC_A
                % 14 AMP_PYR_A
                % 15 ECOG1_V
                % 16 ECOG2_V
                % 17 ECOG3_V
                % 18 ECOG4_V
                % 19 ECOG5_V
                % 20 ECOG6_V
                % 21 EEG1_V
                % 22 EEG2_V

                time_s = values(3);
                cv_potential = values(4);

                pot_k_v = values(11);

                I_GLU = values(12);
                I_LAC = values(13);
                I_PYR = values(14);

                ECOG1 = values(15);
                EEG1 = values(21);

                subplot(4,1,1);
                addpoints(cvLine, time_s, cv_potential);

                subplot(4,1,2);
                addpoints(gluLine, time_s, I_GLU);
                addpoints(lacLine, time_s, I_LAC);
                addpoints(pyrLine, time_s, I_PYR);

                subplot(4,1,3);
                addpoints(potLine, time_s, pot_k_v);

                subplot(4,1,4);
                addpoints(ecogLine, time_s, ECOG1);
                addpoints(eegLine, time_s, EEG1);

                drawnow limitrate;

            else
                badPackets = badPackets + 1;
            end

        else
            disp("Arduino: " + line);
        end
    end
end

%% =========================
% Stop Arduino
% ==========================

sendCommand(s, "STOP");
sendCommand(s, "STATUS");

%% =========================
% Save clean data
% ==========================

if isempty(dataMatrix)
    warning("No valid data received. Files were not saved.");
else
    T = array2table(dataMatrix, "VariableNames", columnNames);

    writetable(T, csvFilename);
    writetable(T, excelFilename);

    disp(" ");
    disp("Saved clean CSV file:");
    disp(csvFilename);

    disp("Saved Excel file:");
    disp(excelFilename);
end

%% =========================
% Verification summary
% ==========================

disp(" ");
disp("===== COMBINED INTERROGATION VERIFICATION SUMMARY =====");

expectedPackets = duration_s * fs;
packetLossEstimate = 100 * (1 - validPackets / expectedPackets);

fprintf("Mode: %s\n", mode);
fprintf("Requested sampling rate: %.2f Hz\n", fs);
fprintf("Duration: %.2f s\n", duration_s);
fprintf("Expected packets: %.0f\n", expectedPackets);
fprintf("Received valid packets: %d\n", validPackets);
fprintf("Bad packets: %d\n", badPackets);
fprintf("Estimated packet loss: %.2f %%\n", packetLossEstimate);

if ~isempty(dataMatrix)
    time_s = dataMatrix(:,3);
    dt = diff(time_s);

    if numel(dt) > 2
        measuredFs = 1 / mean(dt);
        jitter_ms = std(dt) * 1000;

        fprintf("Measured sampling rate: %.2f Hz\n", measuredFs);
        fprintf("Timing jitter, std: %.4f ms\n", jitter_ms);
    end

    sampleCounter = dataMatrix(:,1);
    discontinuities = sum(diff(sampleCounter) ~= 1);
    fprintf("Sample counter discontinuities: %d\n", discontinuities);

    cv_potential = dataMatrix(:,4);
    dac_voltage = dataMatrix(:,5);

    fprintf("CV potential min: %.4f V\n", min(cv_potential));
    fprintf("CV potential max: %.4f V\n", max(cv_potential));
    fprintf("DAC voltage min: %.4f V\n", min(dac_voltage));
    fprintf("DAC voltage max: %.4f V\n", max(dac_voltage));
end

fprintf("Header received: %d\n", headerReceived);
disp("=======================================================");

%% =========================
% Close serial
% ==========================

clear s;
disp("Serial connection closed.");

%% =========================
% Local functions
% ==========================

function sendCommand(s, cmd)
    writeline(s, cmd);
    pause(0.2);

    while s.NumBytesAvailable > 0
        response = strtrim(readline(s));
        disp(">> " + cmd + " | " + response);
    end
end

function [valid, values] = parseArduinoDataLine(line, numExpectedColumns)
    valid = false;
    values = NaN(1, numExpectedColumns);

    parts = split(line, ",");

    if numel(parts) ~= numExpectedColumns + 1
        return;
    end

    if parts(1) ~= "DATA"
        return;
    end

    for i = 1:numExpectedColumns
        values(i) = str2double(parts(i+1));
    end

    if any(isnan(values))
        return;
    end

    valid = true;
end